name: Deploy to Production

on:
  # Deploy to production when code is pushed to master
  # This includes both direct pushes and merged PRs
  push:
    branches:
      - master

jobs:
  # Build and deploy all apps to production
  deploy-production:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      # Cloudflare configuration
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # Clerk authentication (using dev keys for all environments)
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY_DEV }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_DEV }}
      CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_DEV }}

      # Supabase (using dev for now, will switch to prod when ready)
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL_DEV }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY_DEV }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}

      # Database (using dev for now)
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}

      # Production API URL
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Website-specific secrets
      MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
      NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}
      TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

      # Turborepo caching
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linting
        run: pnpm run lint

      - name: Run Type Checking
        run: pnpm run check-types

      - name: Build Packages
        run: pnpm run build --filter="./packages/*"

      # Deploy all apps to production using Turbo
      - name: Deploy All Apps to Production
        run: |
          echo "🚀 Deploying all apps to production using Turbo..."
          pnpm run deploy:prod

      # Notify deployment success
      - name: Production Deployment Success
        run: |
          echo "✅ Successfully deployed all apps to production"
          echo "🌐 Web App: https://app.foundlyhq.com"
          echo "🌍 Website: https://foundlyhq.com"
          echo "⚡ API: https://api.foundlyhq.com"
          echo "👥 Admin: https://admin.foundlyhq.com"
